var apiUrlPrefix = "https://agvdi3.akij.net:44328/api";
var tokenUrlPrefix = "https://agvdi3.akij.net:44321/api";
var tokenUrl = tokenUrlPrefix + "/token";
var userUrl = apiUrlPrefix + "/user";
var facebookAuth = tokenUrlPrefix + "/userAuth/facebook/";
var gmailAuth = tokenUrlPrefix + "/userAuth/gmail/";
var externalAuthSignIn = tokenUrl + "/external";
var refreshUrl = tokenUrl + "/refresh";
var rolesUrl = tokenUrl + "/roles";