// <auto-generated />
namespace AkijRest.IdentityServer.Repository.Migrations.IdentityServerDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Updateusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updateusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201808161211599_Update user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
